### PR TITLE
[ISSUE-4] Successful request validation quits access phase

### PR DESCRIPTION
**Pull request by alexpopero**

### CODE REVIEW

**Comment by alexpopero** [comment]
@ddascal Take a look !

**Comment by ddragosd** [comment]
I believe this was the intent initially. `ngx.exit(ngx.OK)` quits the current phase handler continuing to run later phases for the current request. This may indeed pose problems for cases when something else needs to be executed in the `access_phase`, after the validation. Is this the case you're trying to achieve here ? If yes there may be [other places](https://github.com/alexpopero/api-gateway-request-validation/blob/154effa3b869aa4bfa9ba6f698997b561710d364/src/lua/api-gateway/validation/factory.lua#L56) to update as well.

At the same time, in case of validation error, the only way this library stops the request is by calling `ngx.exit()` with another status. In that case, the remaining logic in `access_phase` won't be executed.

**Comment by alexpopero** [comment]
@ddragosd That's exactly what I want. In case validation fails here, it's ok to exit the whole request phase.

**Comment by alexpopero** [comment]
@ddascal ping

**Comment by cristianconstantin** [comment]
:+1: 

@ddragosd, `ngx.exit()` will still be called in case of validation errors, so I don't see any harm in applying this change.

**Pull request merged**
